### PR TITLE
fix: Remove DeviceProfileBasicInfo fieldName from validation error me…

### LINKED ISSUE #735: Remove the inline struct DeviceProfileBasicInfo of DeviceProfile from the error messages
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
core-metadata DeviceProfile dto

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]
The DeviceProfileBasicInfo is embedded in DeviceProfile, so it should be hidden in the error messages.

## 🔥 Exception or Error

For example, 

> {"apiVersion":"v2","message":"DeviceProfileRequest.Profile.DeviceProfileBasicInfo.Name field only allows unreserved characters which are ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_~","statusCode":400}

The DeviceProfileBasicInfo should be removed.

> {"apiVersion":"v2","message":"**DeviceProfileRequest.Profile.Name** field only allows unreserved characters which are ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_~","statusCode":400}

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by jinlinGuan**
fix #735 

Signed-off-by: Ginny Guan <ginny@iotechsys.com>

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) NA, only update error message
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) NA, only update error message
  <link to docs PR>

## Testing Instructions

1. Build core-metadata from this branch and run with other edgex services
2. Create a profile with invalid name
3. Verify `DeviceProfileBasicInfo` is not included in the response

### CODE REVIEW

File: dtos/deviceprofile.go [hunk 1]
```diff
@@ -27,7 +28,8 @@ type DeviceProfile struct {
 func (dp *DeviceProfile) Validate() error {
 	err := common.Validate(dp)
 	if err != nil {
-		return errors.NewCommonEdgeX(errors.KindContractInvalid, "invalid DeviceProfile.", err)
+		err = errors.New(strings.ReplaceAll(err.Error(), ".DeviceProfileBasicInfo", ""))
```
Comment (cloudxxx8) [inline dtos/deviceprofile.go:31]: add a comment before this line
` // The DeviceProfileBasicInfo is the internal struct in Golang programming, not in the Profile model, so it should be hidden from the error messages.`

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]

**Review by cloudxxx8 — APPROVED** [review]
LGTM
