### PR TITLE
fix(v2): Correct UpdateSubscription DTO validation tags

### LINKED ISSUE #497: [V2] Correct Subscription DTO validation tags
https://github.com/edgexfoundry/go-mod-core-contracts/blob/cdf6f9724aa4f5637705aab0063dc882d2a96c4e/v2/dtos/subscription.go#L34-L35

- `omitempty` should be removed
- use `edgex-dto-uuid` instead of `uuid`

### PR DESCRIPTION
**Pull request by FelixTing**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/.github/Contributing.md.

## What is the new behavior?
- Currently, the validation tag `required_without` can not work correctly with `uuid`, so use the customized tag `edgex-dto-uuid` instead.
- With the `required_without` tag, the `Id` field under validation must be present and not empty only when the `Name` field is not present, and vice versa. So the `omitempty` tag must be removed.

Close #497 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

### CODE REVIEW

File: v2/dtos/subscription.go [hunk 1]
```diff
@@ -31,8 +31,8 @@ type Subscription struct {
 // https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/UpdateSubscription
 type UpdateSubscription struct {
 	common.Versionable `json:",inline"`
-	Id                 *string   `json:"id" validate:"omitempty,required_without=Name,uuid"`
-	Name               *string   `json:"name" validate:"omitempty,required_without=Id,edgex-dto-none-empty-string,edgex-dto-rfc3986-unreserved-chars"`
+	Id                 *string   `json:"id" validate:"required_without=Name,edgex-dto-uuid"`
+	Name               *string   `json:"name" validate:"required_without=Id,edgex-dto-none-empty-string,edgex-dto-rfc3986-unreserved-chars"`
 	Channels           []Channel `json:"channels" validate:"omitempty,dive"`
 	Receiver           *string   `json:"receiver" validate:"omitempty,edgex-dto-none-empty-string,edgex-dto-rfc3986-unreserved-chars"`
```
Comment (cloudxxx8) [inline v2/dtos/subscription.go:37]: omitempty has to be moved to the json part

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]

**Review by cloudxxx8 — APPROVED** [review]
LGTM
