### PR TITLE
Fixed bug in urlClient retry algorithm causing positive condition to never occur

### LINKED ISSUE #220: URLClient's retry function will never be successful
Because of some inverted logic on the boolean gates, the success clause in retry will never execute.

Additionally, the units of time are inconsistent and cause huge waiting periods.

Related: https://github.com/edgexfoundry/edgex-go/issues/2399

edgex-go and app-functions-sdk will need to be updated to include new contracts version.

The outstanding PR is device-sdk will need to be updated to include new contracts version.

### PR DESCRIPTION
**Pull request by brandonforster**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

Issue Number: Fixes #220

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by akramtexas** [comment]
@brandonforster Please help me understand your rationale for the conversion of time units of `Millisecond`, for example here: `tickTime:      time.Duration(interval) * time.Millisecond,` - I did notice the comment in the related issue (`Additionally, the units of time are inconsistent and cause huge waiting periods.`) - It's not clear what exactly was the discrepancy in the time units...

File: clients/urlclient/retry/client_test.go [hunk 1]
```diff
@@ -35,10 +35,12 @@ func TestNew(t *testing.T) {
 
 func TestRegistryClient_Prefix_Periodic(t *testing.T) {
```
Comment (akramtexas) [inline clients/urlclient/retry/client_test.go]: The unit tests run and pass locally ✅
